### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by smoliji**

### CODE REVIEW

**Comment by smoliji** [comment]
Whoever be interested, my other ideas can be viewed [here](https://drive.google.com/file/d/1bVHclQjhx8gzdrESXbqHUGEGa8___Tvr/view?usp=sharing)

**Comment by grissius** [comment]
Personally I would go for something simpler, more flat and less 15 years ago.


Like this for reference:
image


I would get rid of the gradients and overlaying opacity. Just like the black and white in the upper right corner. Just with solid colors and without the 1pt black border around the white border of the stars.

But that's just a suggestion, we can easily go with this for the time being :smiley_cat:

**Comment by smoliji** [comment]
But where is the bless?

**Comment by smoliji** [comment]
I don't like my proposals anymore!

**Pull request closed without merging**
